version: "3.7"

services:
  giyera.io.local:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./:/usr/src/web/
      - media_volume:/usr/src/web/mediafiles
      - static_volume:/usr/src/web/staticfiles
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - db

  node:
    image: node:12-alpine
    entrypoint: ./node.sh
    working_dir: /usr/src/node
    volumes:
      - ./assets:/usr/src/node/assets
      - ./static:/usr/src/node/static
      - ./package.json:/usr/src/node/package.json
      - ./yarn.lock:/usr/src/node/yarn.lock
      - ./webpack.config.js:/usr/src/node/webpack.config.js
      - ./node.sh:/usr/src/node/node.sh
      - ./.env:/usr/src/node/.env
      - node_modules:/usr/src/node/node_modules
    depends_on:
      - giyera.io.local
    env_file:
      - ./.env

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=giyera
      - POSTGRES_USER=giyera_user
      - POSTGRES_PASSWORD=giyera_password

  redis:
    image: redis:6.2.5-alpine

volumes:
  media_volume:
  static_volume:
  node_modules:
  postgres_data:
