# Generated by Django 3.2.5 on 2021-08-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_create_lead_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('player1_id', models.CharField(max_length=255)),
                ('player2_id', models.CharField(max_length=255)),
            ],
        ),
    ]
