# Generated by Django 3.2.5 on 2021-08-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_make_code_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
